#!/bin/sh

usage() {
	cat <<EOF >&2
$0 [-l url] [-u username] [-p] [--] [curl args...]

-l url		the url (default: http://localhost:8070)
-u username	the username to login (default: admin)
-p		prompt for password (default: password)
EOF
}

url=http://localhost:8070
username=admin
password=password
pass_prompt=

while getopts l:u:p option
do
	case $option in
	l) url="$OPTARG";;
	u) username="$OPTARG";;
	p) pass_prompt=1;;
	?) usage; exit 2;;
	esac
done
shift $(($OPTIND - 1))
curlargs=$@

if [ ! -z "$pass_prompt" ]
then
	echo -n "Enter password for $username: "
	stty_orig=`stty -g`
	stty -echo
	read password
	stty $stty_orig
	echo
fi

IFS= curlout=`curl $curlargs -isS -H "Content-Type: application/json" -X POST -d "{
    \"username\": \"$username\",
    \"password\": \"$password\"
}" "$url/login"`
token=`echo $curlout |  awk -F 'Bearer ' '/^[aA]uth/ { print $2 }'`

if [ -z $token ]
then
	echo "Authentication failed" >&2
	echo $curlout >&2
	exit 1
fi

echo export TOKEN=$token
echo export VEOURL=$url

if which xclip 2>/dev/null
then
	echo $TOKEN | xclip -selection clipboard
fi
