#!/bin/sh
#
# usage: ./authenticate [username [password [curl args]]]

USERNAME=${1:-admin}
PASSWORD=${2:-password}

shift
shift

curl -i $@ -H "Content-Type: application/json" -X POST -d "{
    \"username\": \"$USERNAME\",
    \"password\": \"$PASSWORD\"
}" http://localhost:8070/login
