veo:
  cors:
    origins: https://*.verinice.example, https://frontend.somewhereelse.example
  etag:
    salt: rl2xo5fVE3$rf
  message:
    consume:
      autoDelete: 'true'
    dispatch:
      routing-key-prefix: 'veo.resttestmessage.'
  resttest:
    baseUrl: '' # i.e. "https://veo.develop.verinice.com". Leave empty for local tests.
    oidcUrl: 'https://keycloak.staging.verinice.com/auth'
    realm: 'realm'
    clientId: 'clientid'
    veo-clientid: '21712604-ed85-4f08-aa46-1cf39607ee9e'
    veo-secondary-clientid: '26ab39fb-d846-4f47-84a9-98b9aaa64419'
    users:
      default:
        name: ''
        pass: ''
      admin:
        name: ''
        pass: ''
      content-creator:
        name: ''
        pass: ''
      read-only:
        name: ''
        pass: ''
      secondary-client:
        name: ''
        pass: ''
    proxyHost: cache.int.company.de
    proxyPort: 3128

spring:
  datasource:
    url: 'jdbc:postgresql://127.0.0.1:5432/veoresttest'
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.staging.verinice.com/auth/realms/verinice-veo
          jwk-set-uri: https://keycloak.staging.verinice.com/auth/realms/verinice-veo/protocol/openid-connect/certs

  rabbitmq:
    host: localhost # can be a forwarded port
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    context-path: /veoresttest/